config/routes.rb
Rails.application.routes.draw do
  resources :portfolios
  resources :blogs
  get 'contact', to: "pages#contact"
  get 'about', to: "pages#about"
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
    @portfolios = Portfolio.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolios = Portfolio.all
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end

  def new
    @portfolio = Portfolio.new
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  def create
    @portfolio = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body))

    if @portfolio.save
      flash[:notice] = "Portfolio was created successfully"
      redirect_to portfolios_path
    else
      render :new
    end
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.update(params.require(:portfolio).permit(:title, :subtitle, :body))
      flash[:notice] = "Portfolio was updated successfully"
      redirect_to portfolios_path
    else
      render :edit
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy
    redirect_to portfolios_path
    flash[:notice] = "Portfolio was successfully deleted"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog %>
    </p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuflihPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

<h1>Portfolios</h1>
<%= @portfolios.inspect %>

app/views/portfolios/edit.html.erb
<h1>Edit a Portfolio item</h1>

<%= form_for(@portfolio) do |f| %>
  <div>
    <%= f.label :title, style: "display: block;" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :subtitle, style: "display: block;" %>
    <%= f.text_field :subtitle %>
  </div>
  <div>
    <%= f.label :body, style: "display: block;" %>
    <%= f.text_area :body %>
  </div>
  <div style="margin-top: 10px;">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<p><%= notice %></p>

<h1>Portfolio items</h1>

<%= link_to "Create new Portfolio", new_portfolio_path %>

<% @portfolios.each do |portfolio| %>
  <h2><%= link_to portfolio.title, portfolio_path(portfolio) %></h2>
  <p><%= portfolio.subtitle %></p>
  <%= image_tag portfolio.thumbnile_image if !portfolio.thumbnile_image.nil? %>
  <p><%= portfolio.body %></p>
  <%= link_to "Show this Portfolio", portfolio_path(portfolio) %>
  <span> |||| </span>
  <%= link_to "Edit this Portfolio", edit_portfolio_path(portfolio) %>
  <span> |||| </span>
  <span style="display: inline-block;">
    <%= button_to "Delete this Portfolio", portfolio_path(portfolio), method: :delete, data: { confirm: "Are you sure"} %>
  </span>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio item</h1>

<%= form_for(@portfolio) do |f| %>
  <div>
    <%= f.label :title, style: "display: block;" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :subtitle, style: "display: block;" %>
    <%= f.text_field :subtitle %>
  </div>
  <div>
    <%= f.label :body, style: "display: block;" %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit style: "margin-top: 10px;" %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<p><%= notice %></p>

<h1>Portfolio show page</h1>

<hr />

<%= image_tag @portfolio.main_image if !@portfolio.main_image.nil? %>
<h2><%= @portfolio.title %></h2>
<em><%= @portfolio.subtitle %></em>
<p><%= @portfolio.body %></p>

<%= link_to "Back Portfolios", portfolios_path %> <span> |||| </span>
<%= link_to "Edit", edit_portfolio_path(@portfolio) %>
<span> |||| </span>
<span style="display: inline-block;">
  <%= button_to "Delete", portfolio_path(@portfolio), method: :delete %>
</span>